### ISSUE TITLE
接收错误

### ISSUE THREAD

**Issue by fyhbauyg** [kmod-midori/CatShare#28]
[lineageos19.txt](https://github.com/user-attachments/files/20637732/lineageos19.txt)

[miui13.txt](https://github.com/user-attachments/files/20637733/miui13.txt)
当接收端直接在磁铁打开接受服务时，接收端没有提示是否接收文件且会出现p2p之类的错误字样提示
，接收端打开应用在发送文件时正常接收速度每秒150mb，双端均是，且使用sui授权。
另外，可否增加一项配置，自定义接收后保存文件位置。
机型oppoa92s 5g和红米note11 5g

**Comment by fyhbauyg** [comment]
> ![lineageos19.txt](https://github.com/user-attachments/files/20637732/lineageos19.txt)
> 
> ![miui13.txt](https://github.com/user-attachments/files/20637733/miui13.txt)
> 当接收端直接在磁铁打开可被发现的服务时，接收端没有提示是否接受文件且会出现p2p之类的错误字样提示
> ，接收端打开应用在发送文件时正常接收速度每秒150mb，双端均是，且使用sui授权。
> 另外，可否增加一项配置，自定义接收后保存文件位置。
> 机型oppoa92s 5g和红米note11 5g

补充信息![Screenshot_20250607-163024_Trebuchet.png](https://github.com/user-attachments/assets/a24a59ea-6050-4e04-8222-5920e56bfe37)

oppoa92s 5g是lineageos19，红米note11 5g是miui13。

**Comment by kmod-midori** [comment]
怀疑是什么奇怪的后台限制，我最近没有条件做调试，下个月处理一下

**Comment by fyhbauyg** [comment]
> 怀疑是什么奇怪的后台限制，我最近没有条件做调试，下个月处理一下

看到你的答复后我就把两台手机的catshare电池优化都关了，还是报错，但是变了。
![Screenshot_20250609-023311_Lawnchair.png](https://github.com/user-attachments/assets/805213ba-ecf2-48a1-b46a-dbd3d64b9175)

**Comment by fyhbauyg** [comment]
> 怀疑是什么奇怪的后台限制，我最近没有条件做调试，下个月处理一下

我在给备用机做华为推送的时候传输hmscore，这次连打开软件都传输不了了。
![Screenshot_20250610-011646_CatShare.png](https://github.com/user-attachments/assets/73088a57-abc2-4978-931f-9ee3c719b56b)
[lineageos.txt](https://github.com/user-attachments/files/20658722/lineageos.txt)
我的网络是nat1和upup按理来说不会有这么多问题的，真的好奇怪。

**Comment by fyhbauyg** [comment]
> Hello, I have the same issue.

This error was fixed by my pull request

**Comment by Mrunknown-da** [comment]
> > Hallo, ich habe das gleiche Problem.
> 
> Dieser Fehler wurde durch meinen Pull Request behoben

Where can I download the release?

**Comment by fyhbauyg** [comment]
> @Mrunknown-da For the time being, try setting location permission to "always allow" for this app in settings (if it is there). Please tell me if there are no such option.
> 
> @fyhbauyg 后台位置的申请流程还有点绕，我周末如果不加班的话实现一下（已经加了两周的班了...）

辛苦大佬，可以暂时给readme添加备注后台接收文件需要手动给位置权限设置成始终允许

**Comment by Mrunknown-da** [comment]
I modified the androidmanifest.xml to ask for that permission, but it still doesn't work. Maybe I have an other error. I don't really understand everything of this issue, because the translator is bad.

**Comment by fyhbauyg** [comment]
> I modified the androidmanifest.xml to ask for that permission, but it still doesn't work. Maybe I have an other error. I don't really understand everything of this issue, because the translator is bad.

[fix this issue pull](https://github.com/kmod-midori/CatShare/pull/30)

**Comment by fyhbauyg** [comment]
> > > I modified the androidmanifest.xml to ask for that permission, but it still doesn't work. Maybe I have an other error. I don't really understand everything of this issue, because the translator is bad.
> > 
> > [fix this issue pull](https://github.com/kmod-midori/CatShare/pull/30)
> 
> Sorry, I don't really understand what I should do...

add```
<uses-permission  
         android:name="android.permission.ACCESS_BACKGROUND_LOCATION" 
         android:maxSdkVersion="32" />
```

**Comment by Mrunknown-da** [comment]
Still doesn't work on my devices (catshare device: s5 with crdroid Android 12 , 
receiver: Xiaomi Pad 6 with hyperos 2 global.)
Maybe it's because of MIUI global, but I'm not sure.

**Comment by fyhbauyg** [comment]
@Mrunknown-da Have you manually set location permissions to always allow?
